---

- hosts: all
  become: true
  pre_tasks:

  - name: Install update (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Update repository index (CentOS)
    yum:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install Java on Ubuntu
    apt:
      name: openjdk-11-jdk
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Install Java on CentOS
    yum:
      name: java-11-openjdk
      state: present
    when: ansible_distribution == "CentOS"

  - name: Install UFW
    become: yes
    apt:
      name: ufw
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Enable UFW
    become: yes
    apt:
      name: ufw
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Update apt
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Epel-release
    yum:
      update_cache: yes
      update_only: yes
    when: ansible_distribution == "CentOS"

- hosts: elastic_search
  become: true
  roles:
    - elastic_search

- hosts: kibana
  become: true
  roles:
    - kibana

- hosts: logstash
  become: true
  roles:
    - logstash

